version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  checkoutEtTests:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Installer les dépendances
          command: npm install
      - run:
          name: Exécuter les tests
          command: npm test

  integrationFrontend:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Cloner le frontend
          command: git clone https://github.com/Nokam2025/L01-frontend 
      - run:
          name: Installer les dépendances du frontend
          command: |
            cd L01-frontend
            npm install
      - run:
          name: Build du frontend
          command: |
            cd L01-frontend
            npm run build
      - run:
          name: Déplacer le build dans le backend
          command: |
            mkdir -p public
            cp -r L01-frontend/build/* public/
      - persist_to_workspace:
          root: .
          paths:
            - public

  deploiement:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Vérification du répertoire backend après intégration
          command: ls -R public

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkoutEtTests
      - integrationFrontend:
          requires:
            - checkoutEtTests
      - deploiement:
          requires:
            - integrationFrontend
